[project]
name = "module1"
authors = []
description = ""
telemetry = false
requirements = []
cache_dir = "/Users/fanjum/Documents/web3/stacks_sc/projects/my_projs/Clarity-L2/module1/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.M2]
path = "contracts/M2.clar"
depends_on = ['edu-token']

[contracts.edu-token]
path = "contracts/edu-token.clar"
depends_on = ['edu-token-trait']

[contracts.edu-token-trait]
path = "contracts/edu-token-trait.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

