[project]
name = "module1"
authors = []
description = ""
telemetry = false
requirements = []
cache_dir = "/Users/fanjum/Documents/web3/stacks_sc/projects/my_projs/Clarity-L2/module1/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.M1]
path = "contracts/M1.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
